// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication6.Data;

#nullable disable

namespace WebApplication6.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250723071034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication6.Models.FicheDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accessoires")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commentaires")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FicheProjetId")
                        .HasColumnType("int");

                    b.Property<string>("TravauxPromamec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FicheProjetId")
                        .IsUnique();

                    b.ToTable("FicheDetails");
                });

            modelBuilder.Entity("WebApplication6.Models.FicheMetaDonnee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("FicheProjetId")
                        .HasColumnType("int");

                    b.Property<string>("SessionMachine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FicheProjetId");

                    b.ToTable("FicheMetaDonnees");
                });

            modelBuilder.Entity("WebApplication6.Models.FicheModification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AncienneValeur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChampsModifie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<int>("FicheProjetId")
                        .HasColumnType("int");

                    b.Property<string>("NouvelleValeur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FicheProjetId");

                    b.ToTable("FicheModifications");
                });

            modelBuilder.Entity("WebApplication6.Models.FicheProjet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ContratMaintenance")
                        .HasColumnType("bit");

                    b.Property<string>("ContratNumero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DernierDelaiExecution")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DernierDelaiLivraison")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailFormation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DossierAMSSNUR")
                        .HasColumnType("bit");

                    b.Property<string>("DureeGarantie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModalitePaiement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroAffaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroProjet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FicheProjets");
                });

            modelBuilder.Entity("WebApplication6.Models.FicheDetail", b =>
                {
                    b.HasOne("WebApplication6.Models.FicheProjet", "FicheProjet")
                        .WithOne("Detail")
                        .HasForeignKey("WebApplication6.Models.FicheDetail", "FicheProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FicheProjet");
                });

            modelBuilder.Entity("WebApplication6.Models.FicheMetaDonnee", b =>
                {
                    b.HasOne("WebApplication6.Models.FicheProjet", "FicheProjet")
                        .WithMany()
                        .HasForeignKey("FicheProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FicheProjet");
                });

            modelBuilder.Entity("WebApplication6.Models.FicheModification", b =>
                {
                    b.HasOne("WebApplication6.Models.FicheProjet", "FicheProjet")
                        .WithMany()
                        .HasForeignKey("FicheProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FicheProjet");
                });

            modelBuilder.Entity("WebApplication6.Models.FicheProjet", b =>
                {
                    b.Navigation("Detail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
